### PR TITLE
Output phase-data quakeml for quakeml detail

### LINKED ISSUE #98: Update quakeml detail search to return contributed quakeml
Find the phase-data product if available, use origin otherwise.

Find the quakeml with the requested event id.
Return non-preferred quakeml if requested using non-preferred id.

@jmfee-usgs can you provide more information on this?

### PR DESCRIPTION
**Pull request by jmfee-usgs**
fixes #98

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
If a product is not backed by quakeml, what then? For example: `at00o1gd6r` is based on eqxml. Currently the code throws an exception. I think either:

(1) Serve the old quakeml output that would have previously been generated
(2) Serve the eqxml.xml file (if it exists)
or
(3) Serve some sort of http error code indicating the problem.

I don't care much on how it's handled, but it ought be handled in some way so the user does not receive a blank white page.

**Comment by jmfee-usgs** [comment]
This better handles the case where a product is not submitted in quakeml.  The following is the expected output:

1) quakeml from phase-data for given eventid if it exists
2) quakeml from origin for given eventid if it exists
3) fall back to auto generate quakeml for the event (same as quakeml summary feed for event) based on product information.
4) if no event exists, standard FDSN error handling: `204` response code by default, `404` if `nodata` parameter overrides...

**Comment by emartinez-usgs** [comment]
Nothing in the issue or pull request comments suggest that we should fall back to serving the static QuakeML file for the preferred product (phase-data then origin) when the a product (phase-data then origin) matching the requested event id is not found (detail/quakeml.inc.php: L39 - 46).

@jmfee-usgs @llastowka-usgs I don't see this as a problem, it is just not the requested behavior. Is this a good intermediate step?

**Comment by jmfee-usgs** [comment]
Updated to fall through to summary feed when no phase-data/origin product matching requested eventid is found, to match originally intended logic.

**Pull request merged**
